# Generated by Django 5.0.4 on 2024-04-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcompany',
            options={'ordering': ('id',), 'verbose_name': 'Изделие производства', 'verbose_name_plural': 'Изделия производства'},
        ),
        migrations.RemoveField(
            model_name='searchinfo',
            name='group_paths',
        ),
        migrations.AddField(
            model_name='searchinfo',
            name='groups_paths',
            field=models.ManyToManyField(to='app.grouppaths', verbose_name='Группы путей'),
        ),
        migrations.AlterField(
            model_name='productcompany',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='GroupPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Обратный путь')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.path', verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Путь заказа',
                'verbose_name_plural': 'Пути заказа',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GroupPathsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grouppath', verbose_name='Путь заказа')),
                ('group_paths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grouppaths', verbose_name='Группа путей')),
            ],
            options={
                'verbose_name': 'Связь группы путей и пути заказа',
                'verbose_name_plural': 'Связи группы путей и пути заказа',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='grouppaths',
            name='paths',
            field=models.ManyToManyField(through='app.GroupPathsRelation', to='app.grouppath', verbose_name='Пути'),
        ),
        migrations.DeleteModel(
            name='PathGroup',
        ),
    ]
