# Generated by Django 5.0.4 on 2024-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_grouppaths_warehouse_alter_order_decline_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchinfo',
            options={'ordering': ('id',), 'verbose_name': 'Информация о поиске', 'verbose_name_plural': 'Информации о поиске'},
        ),
        migrations.AddField(
            model_name='pointincity',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
