# Generated by Django 5.0.4 on 2024-04-12 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_image_alter_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppaths',
            name='instant_city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name='Город мгновенной доставки'),
        ),
        migrations.AddField(
            model_name='grouppaths',
            name='is_instant_delivery',
            field=models.BooleanField(default=False, verbose_name='Мгновенная доставка'),
        ),
    ]
